# This file was generated by GoReleaser. DO NOT EDIT.
cask "arc" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2a9792a458e9b1a7829588cbf30982865e0cc00fee4acfc734b5dfc5d98909dc"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "63ab5b44a577f610277dd7cb35d77f513b4b3d29dd4637d18f51355de97be5db"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dbf6650efa94ee95b7265ab25f7c4cd56e43f8cb06407e99b3e8ce078ece5f15"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec12e08578fbd3510e0658c829c3fa4e69bce390bdbdc2af095a0e261c64dc93"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_linux_arm64.tar.gz"
    end
  end

  name "arc"
  desc "Version your agent's context like git versions code."
  homepage "https://github.com/Dieg0Code/arc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arc"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arc"]
    end
  end

  # No zap stanza required

end
