# This file was generated by GoReleaser. DO NOT EDIT.
cask "arc" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3e177c431e80fc9e168d8de702b431f5b3020d74eb268c4436b679fd9e70c468"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b75e8839078da82e84cf72b81046decc71d5d9a6fd8cecefcb625174ca22936f"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "782e8c40ef66c309513e4c44327cc9c503e116c1ca0abc77d53f16be4fb5c8c9"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3068d9afef04e27752822e7b11a1336915916e2fa1cae40d30ac678a1a3713bd"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_linux_arm64.tar.gz"
    end
  end

  name "arc"
  desc "Version your agent's context like git versions code."
  homepage "https://github.com/Dieg0Code/arc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arc"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arc"]
    end
  end

  # No zap stanza required

end
