# This file was generated by GoReleaser. DO NOT EDIT.
cask "arc" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ba36f096e3ced0d46ea70a22dc4fc9ec3ff7e394403ba6ddcf480e73346a0e1b"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7bf650a6e00c755fa5720881292da9eb6051b8e226949d4a9b3048aa32a4d70"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0a1fb351ed54a8be6f5fb74be5a003207b9f4b678d92549f907c0e325b3aa53"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b0b76a3094dec92791c4ea34da6b5e4355fb776c17ed3db1fe27d0b07ff29e3a"
      url "https://github.com/Dieg0Code/arc/releases/download/v#{version}/arc_linux_arm64.tar.gz"
    end
  end

  name "arc"
  desc "Version your agent's context like git versions code."
  homepage "https://github.com/Dieg0Code/arc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arc"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arc"]
    end
  end

  # No zap stanza required

end
