# This file was generated by GoReleaser. DO NOT EDIT.
cask "nem" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "9103baa857571bfdc8332c189e3426721dfe2047036d8e3b534ea36fef7deb9d"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15b0b094c43206e6f76b45f42853720b0afbb118ac348131be5b4ce20343b508"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25ea0051141c8506cd71c02d66dd97035eca1b67a1f640f71bd72a58b071d961"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e67b742d33747ebc743ffdb65c0d23b9fc7866e99adaebe9057a81617d82c844"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_linux_arm64.tar.gz"
    end
  end

  name "nem"
  desc "Version your agent's context like git versions code."
  homepage "https://github.com/Dieg0Code/nem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nem"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nem"]
    end
  end

  # No zap stanza required

end
