# This file was generated by GoReleaser. DO NOT EDIT.
cask "nem" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "07731f9ce4c24e6df6ef3a417072abbf6da48d2c468f24d6705e31f524e98624"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0469b746a58b0c0a2df3e52274d58cf61b34f2658dabf455c60833daff3f6ae"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b947e785627781e19ea08c64164b134c8344bf7e6c9cb679798ee125c7f2d0c"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1a5fe3a37ad6cd59b6f0c87bf5c23d035a48499434f6c5326febe9d70d91193"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_linux_arm64.tar.gz"
    end
  end

  name "nem"
  desc "Git-style versioned memory for AI coding agents (Claude Code, Codex, Antigravity & opencode)."
  homepage "https://github.com/Dieg0Code/nem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nem"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nem"]
    end
  end

  # No zap stanza required

end
