# This file was generated by GoReleaser. DO NOT EDIT.
cask "nem" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "7d4b3d949acfbd11bfe6952beef99c7a99151230bdcf9f72a7ce0964a00d9f0c"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a84d28575009390333639f19be8ef7db51d9513d62f921b65e330450e0679b5b"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66b0c30b0f5ef9b5c59ba6ecb637c564f4a2fd62789e98bb0c5b8a798d73cc93"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "948c739f8cb965d08a90a36b264cfa94ec58f6d27d86a5e06b2ac58e10c7ed20"
      url "https://github.com/Dieg0Code/nem/releases/download/v#{version}/nem_linux_arm64.tar.gz"
    end
  end

  name "nem"
  desc "Git-style versioned memory for AI coding agents (Claude Code, Codex & Antigravity)."
  homepage "https://github.com/Dieg0Code/nem"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nem"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nem"]
    end
  end

  # No zap stanza required

end
